// <auto-generated />
namespace App.BluePrint.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Metadata_GroupSection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Metadata_GroupSection));
        
        string IMigrationMetadata.Id
        {
            get { return "201503191227592_Metadata_GroupSection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
